script: |
  cd /home/ec2-user || exit

  # Clone repo if not exists
  if [ ! -d "ensafe" ]; then
    git clone https://github.com/Jkarthikeyan003/ensafe.git
  fi

  cd ensafe

  # Pull latest changes
  git pull origin main

  # Install dependencies
  npm install

  # Restart app properly
  pm2 delete express-app || true
  pm2 start app.js --name express-app

  pm2 save